auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:month-:day-:year/:title.html

title: Start
url: http://zhouhengmin.github.io
author_info: <a href="http://zhouhengmin.github.io">zhm</a>

