title:            test
description:      test the blog
url:              
baseurl:          # Base url. ( if use subdirectory-like URL )
signoff:          test # Your name.
disqus_shortname: test # disqus comment thread for post header options. ( leave blank if unwanted. )
google_analytics_id: # set tracking, UA-XXXX-Y.
encoding: utf-8
links:
  
  - name:         Blog
    url:          /
  - name:         Categories
    url:          /tags
  - name:         GitHub
    url:          http://github.com/test
    external:     true
  - name:         About
    url:          /about

pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:     [autolink, tables]
