title:            时空胶囊
description:      瞬间亦永恒
url:              
baseurl:          # Base url. ( if use subdirectory-like URL )
signoff:          Z. # Your name.
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
google_analytics_id: # set tracking, UA-XXXX-Y.
encoding: utf-8
links:
  
  - name:         Blog
    url:          /
  - name:         Categories
    url:          /tags
  - name:         GitHub
    url:          https://github.com/zhouhengmin/zhouhengmin.github.io
    external:     true
  - name:         About
    url:          /about

pygments:         true
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:     [autolink, tables]
